/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VoAuthDialog: typeof import('./src/components/auth/VoAuthDialog.vue')['default']
    VoAuthDiscord: typeof import('./src/components/auth/VoAuthDiscord.vue')['default']
    VoAuthGithub: typeof import('./src/components/auth/VoAuthGithub.vue')['default']
    VoAuthListItem: typeof import('./src/components/auth/VoAuthListItem.vue')['default']
    VoAuthLogoutListItem: typeof import('./src/components/auth/VoAuthLogoutListItem.vue')['default']
    VoAuthSyncCard: typeof import('./src/components/auth/VoAuthSyncCard.vue')['default']
    VoBtn: typeof import('./src/components/app/VoBtn.vue')['default']
    VoDashboardListItem: typeof import('./src/components/VoDashboardListItem.vue')['default']
    VoDialog: typeof import('./src/components/app/VoDialog.vue')['default']
    VoDiscordLogin: typeof import('./src/components/auth/VoDiscordLogin.vue')['default']
    VoFooter: typeof import('./src/components/app/VoFooter.vue')['default']
    VoGithubLogin: typeof import('./src/components/auth/VoGithubLogin.vue')['default']
    VoListItem: typeof import('./src/components/app/VoListItem.vue')['default']
    VoLogoutListItem: typeof import('./src/components/VoLogoutListItem.vue')['default']
    VoNotificationList: typeof import('./src/components/notifications/VoNotificationList.vue')['default']
    VoNotificationsDialog: typeof import('./src/components/notifications/VoNotificationsDialog.vue')['default']
    'VoNotificationsDialog.1': typeof import('./src/components/VoNotificationsDialog.1.vue')['default']
    VoNotificationsList: typeof import('./src/components/notifications/VoNotificationsList.vue')['default']
    VoNotificationsListItem: typeof import('./src/components/notifications/VoNotificationsListItem.vue')['default']
    VoSettingsDialog: typeof import('./src/components/settings/VoSettingsDialog.vue')['default']
    VoSettingsListItem: typeof import('./src/components/settings/VoSettingsListItem.vue')['default']
    VoSponsorshipListItem: typeof import('./src/components/sponsorships/VoSponsorshipListItem.vue')['default']
    VoSponsorshipsDialog: typeof import('./src/components/sponsorships/VoSponsorshipsDialog.vue')['default']
    VoSponsorshipsListItem: typeof import('./src/components/sponsorships/VoSponsorshipsListItem.vue')['default']
    VoSubscriptionDialog: typeof import('./src/components/subscription/VoSubscriptionDialog.vue')['default']
    VoSubscriptionInvoices: typeof import('./src/components/subscription/VoSubscriptionInvoices.vue')['default']
    VoSubscriptionListItem: typeof import('./src/components/subscription/VoSubscriptionListItem.vue')['default']
    VoSubscriptionPerks: typeof import('./src/components/subscription/VoSubscriptionPerks.vue')['default']
    VoSubscriptionStatus: typeof import('./src/components/subscription/VoSubscriptionStatus.vue')['default']
    VoSubscriptionSubscribe: typeof import('./src/components/subscription/VoSubscriptionSubscribe.vue')['default']
    VoSwitch: typeof import('./src/components/app/VoSwitch.vue')['default']
    VoSyncCard: typeof import('./src/components/VoSyncCard.vue')['default']
    VoUserAvatar: typeof import('./src/components/user/VoUserAvatar.vue')['default']
    VoUserBtn: typeof import('./src/components/user/VoUserBtn.vue')['default']
    VoUserList: typeof import('./src/components/user/VoUserList.vue')['default']
    VoUserMenu: typeof import('./src/components/user/VoUserMenu.vue')['default']
    VoUserQuickActions: typeof import('./src/components/user/VoUserQuickActions.vue')['default']
  }
}
