packages:
  - packages/*

catalog:
  '@tsconfig/node22': ^22.0.5
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.15.21
  '@vue/tsconfig': ^0.8.1
  bumpp: ^10.3.2
  eslint: ^9.27.0
  eslint-config-vuetify: ^4.1.0
  happy-dom: ^20.1.0
  lodash-es: ^4.17.21
  pinia: ^3.0.3
  sass: ^1.92.1
  tsdown: ^0.16.8
  typescript: ^5.8.3
  vite: ^7.0.7
  vitest: ^3.2.4
  vue: ^3.5.13
  vue-router: ^4.5.1
  vue-tsc: ^3.0.6
  vuetify: ^3.8.0

catalogMode: strict

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver

minimumReleaseAge: 4320
